import { FmsDefinition } from '../_framework/types';

export const orderToDeliveryFms: FmsDefinition = {
  code: 'O2D',
  name: {
    en: 'Order-to-Delivery',
    hi: 'ऑर्डर टू डिलीवरी',
  },
  description: {
    en: 'End-to-end customer order booking, staggered dispatching, and order closure.',
    hi: 'ग्राहक ऑर्डर बुकिंग, चरणबद्ध डिस्पैच और ऑर्डर पूर्णता प्रक्रिया।',
  },
  enable_bill_sequence_tracking: true,
  steps: [
    {
      step_no: 1,
      label: {
        en: 'Order Entry',
        hi: 'ऑर्डर एंट्री',
      },
      assignee: { type: 'DIRECT_USER_PHONE', phone: '9009200757', name: 'Lalita Yadav' },
      is_important: true,
      tat: { kind: 'ANYTIME' },
      questions: [
        {
          key: 'customer_name',
          label: { en: 'Customer Name', hi: 'ग्राहक का नाम' },
          type: 'master_list',
          master_list_key: 'customers',
          required: true,
        },
        {
          key: 'quantity',
          label: { en: 'Order Quantity (Pcs)', hi: 'ऑर्डर मात्रा (पीस)' },
          type: 'number',
          required: true,
        },
        {
          key: 'order_receive',
          label: { en: 'Order Receive Medium', hi: 'ऑर्डर कैसे प्राप्त हुआ' },
          type: 'select',
          options: ['By Phone', 'By Social Media', 'by Self selection on Shop'],
          required: true,
        },
        {
          key: 'products_ordered',
          label: { en: 'Products Ordered', hi: 'ऑर्डर किए गए उत्पाद' },
          type: 'multi_select',
          options: [
            'top/t shirt',
            'Half Bottom',
            'Full Bottom',
            'Capries',
            'Skirts',
            'LongTop/Alines',
            'Sets',
            'Boys',
          ],
          required: true,
        },
        {
          key: 'special_requirements',
          label: { en: 'Special Requirement', hi: 'विशेष निर्देश / विवरण' },
          type: 'text',
          required: false,
        },
        {
          key: 'transport',
          label: { en: 'Transport', hi: 'ट्रांसपोर्ट' },
          type: 'master_list',
          master_list_key: 'transports',
          required: true,
        },
        {
          key: 'agent_name',
          label: { en: 'Agent Name', hi: 'एजेंट का नाम' },
          type: 'master_list',
          master_list_key: 'agents',
          required: false,
        },
        {
          key: 'lead_time_days',
          label: { en: 'Lead Time (In Days)', hi: 'लीड टाइम (दिनों में)' },
          type: 'number',
          required: true,
        },
        {
          key: 'order_rate',
          label: { en: 'Order Rate Type', hi: 'रेट का प्रकार' },
          type: 'select',
          options: ['Net Rate', 'Gross Rate', 'Mix'],
          required: true,
        },
        {
          key: 'discount_percent',
          label: { en: 'Discount % (Regular Customer)', hi: 'डिस्काउंट % (नियमित ग्राहक)' },
          type: 'number',
          required: false,
        },
      ],
      on_complete: 'NEXT',
    },
    {
      step_no: 2,
      label: {
        en: 'Dispatch Entry',
        hi: 'डिस्पैच एंट्री',
      },
      assignee: { type: 'DIRECT_USER_PHONE', phone: '7771002882', name: 'Akash Soni' },
      is_important: true,
      tat: {
        kind: 'DYNAMIC',
        from_step: 1,
        field_key: 'lead_time_days',
        unit: 'DAYS',
      },
      visible_data: [
        'customer_name',
        'quantity',
        'order_receive',
        'products_ordered',
        'special_requirements',
        'transport',
        'agent_name',
        'lead_time_days',
        'order_rate',
        'discount_percent',
      ],
      repeatable: {
        quantity_field: 'qty_dispatched',
        target_field: { from_step: 1, key: 'quantity' },
        auto_complete_at_percent: 120,
        requires_settlement: true,
      },
      questions: [
        {
          key: 'bill_no',
          label: { en: 'Bill No. / Challan No.', hi: 'बिल नंबर / चालान नंबर' },
          type: 'text',
          required: true,
        },
        {
          key: 'customer_verified',
          label: { en: 'Customer Name Cross-Check', hi: 'ग्राहक नाम सत्यापन' },
          type: 'select',
          options: ['Yes Correct', 'No Not Match'],
          required: true,
        },
        {
          key: 'qty_dispatched',
          label: { en: 'Dispatch Quantity (Pcs)', hi: 'डिस्पैच मात्रा (पीस)' },
          type: 'number',
          required: true,
        },
        {
          key: 'transport',
          label: { en: 'Transport Used', hi: 'उपयोग किया गया ट्रांसपोर्ट' },
          type: 'master_list',
          master_list_key: 'transports',
          required: false,
        },
      ],
      on_complete: 'NEXT',
    },
    {
      step_no: 3,
      label: {
        en: 'Complete Order',
        hi: 'ऑर्डर पूर्ण करें',
      },
      assignee: {
        type: 'SHARED_USERS',
        users: [
          { phone: '8109014198', name: 'KR' },
          { phone: '6267888249', name: 'Himanshu Gurjar' },
        ],
      },
      is_important: true,
      tat: { kind: 'FIXED_HOURS', hours: 24 },
      visible_data: [
        'customer_name',
        'quantity',
        'products_ordered',
        'special_requirements',
        'transport',
        'agent_name',
        'order_rate',
      ],
      questions: [
        {
          key: 'order_80_percent_dispatched',
          label: { en: 'Order 80% se jyada dispatch hogaya?', hi: 'क्या ऑर्डर 80% से ज्यादा डिस्पैच हो गया?' },
          type: 'select',
          options: ['Yes / Haan', 'No / Nahi'],
          required: true,
        },
        {
          key: 'confirmed_by_name',
          label: { en: 'Your Name (Confirmer)', hi: 'आपका नाम (पुष्टिकर्ता)' },
          type: 'text',
          required: true,
        },
        {
          key: 'remarks',
          label: { en: 'Closing Remarks / Notes', hi: 'समापन टिप्पणी' },
          type: 'text',
          required: false,
        },
      ],
      on_complete: 'CLOSE',
    },
  ],
};
