import { FmsDefinition } from '../_framework/types';

export const purchaseFms: FmsDefinition = {
  code: 'PUR',
  name: {
    en: 'Purchase Flow',
    hi: 'खरीद प्रक्रिया (Purchase FMS)',
  },
  description: {
    en: 'Fabric requirements, order placement, supplier PO dispatch, inwards quality check, and payment approvals.',
    hi: 'कपड़ा आवश्यकता, ऑर्डर पूर्ति, सप्लायर पीओ, आवक क्वालिटी जांच और भुगतान स्वीकृति।',
  },
  steps: [
    {
      step_no: 1,
      label: { en: 'Fabric Requirements', hi: 'कपड़े की आवश्यकता (Requirements)' },
      assignee: { type: 'DIRECT_USER_PHONE', phone: '9399906456', name: 'Santosh Rajput' },
      is_important: true,
      tat: { kind: 'ANYTIME' },
      questions: [
        {
          key: 'fabric_name',
          label: { en: 'Fabric Name', hi: 'कपड़े का नाम' },
          type: 'master_list',
          master_list_key: 'fabrics',
          required: true,
        },
        {
          key: 'fabric_quantity',
          label: { en: 'Fabric Quantity', hi: 'कपड़े की मात्रा' },
          type: 'number',
          required: true,
        },
        {
          key: 'unit',
          label: { en: 'Unit', hi: 'इकाई' },
          type: 'select',
          options: ['Kg', 'Yards', 'Meter'],
          required: true,
        },
        {
          key: 'color_or_print',
          label: { en: 'Color or Print ?', hi: 'रंग या प्रिंट?' },
          type: 'select',
          options: ['Color', 'Print'],
          required: true,
        },
        {
          key: 'purpose',
          label: { en: 'Purpose', hi: 'उद्देश्य / प्रयोजन' },
          type: 'text',
          required: true,
        },
        {
          key: 'image_url',
          label: { en: 'Image (if any)', hi: 'फोटो / चित्र (यदि कोई हो)' },
          type: 'file',
          required: false,
        },
      ],
      on_complete: 'NEXT',
    },
    {
      step_no: 2,
      label: { en: 'Order Done', hi: 'ऑर्डर डन (Order Done)' },
      assignee: { type: 'DIRECT_USER_PHONE', phone: '8109014198', name: 'KR' },
      is_important: true,
      tat: { kind: 'FIXED_HOURS', hours: 9 },
      visible_data: ['fabric_name', 'fabric_quantity', 'unit', 'color_or_print', 'purpose', 'image_url'],
      questions: [
        {
          key: 'lead_time_days',
          label: { en: 'Lead time (Days)', hi: 'लीड टाइम (दिन)' },
          type: 'number',
          required: true,
        },
        {
          key: 'agent_name',
          label: { en: 'Agent Name', hi: 'एजेंट का नाम' },
          type: 'master_list',
          master_list_key: 'agents',
          required: true,
        },
        {
          key: 'rate',
          label: { en: 'Rate (₹)', hi: 'दर (Rate ₹)' },
          type: 'number',
          required: true,
        },
        {
          key: 'discount_percent',
          label: { en: 'Discount %', hi: 'छूट (Discount %)' },
          type: 'number',
          required: true,
        },
        {
          key: 'order_quantity',
          label: { en: 'Order Quantity', hi: 'ऑर्डर मात्रा' },
          type: 'number',
          required: true,
        },
        {
          key: 'unit',
          label: { en: 'Unit', hi: 'इकाई' },
          type: 'select',
          options: ['Color', 'Kg', 'Yards', 'Meter', 'Prints'],
          required: true,
        },
      ],
      on_complete: 'NEXT',
    },
    {
      step_no: 3,
      label: { en: 'Send PO To Supplier', hi: 'सप्लायर को पीओ भेजें (Send PO)' },
      assignee: { type: 'DIRECT_USER_PHONE', phone: '8839364733', name: 'Sapna Sahu' },
      is_important: true,
      tat: { kind: 'FIXED_HOURS', hours: 6 },
      visible_data: ['fabric_name', 'order_quantity', 'unit', 'rate', 'discount_percent', 'agent_name', 'lead_time_days'],
      questions: [
        {
          key: 'po_sent_confirmation',
          label: { en: 'Have you sent the PO number?', hi: 'क्या आपने पीओ नंबर भेज दिया है?' },
          type: 'select',
          options: ['Yes', 'No'],
          required: true,
        },
      ],
      on_complete: 'NEXT',
    },
    {
      step_no: 4,
      label: { en: 'Inwards & Quality Check', hi: 'माल आवक व क्वालिटी जांच (Quality Check)' },
      assignee: { type: 'DIRECT_USER_PHONE', phone: '9399906456', name: 'Santosh Rajput' },
      is_important: true,
      tat: {
        kind: 'DYNAMIC',
        from_step: 2,
        field_key: 'lead_time_days',
        unit: 'DAYS',
      },
      visible_data: ['fabric_name', 'order_quantity', 'unit', 'agent_name'],
      questions: [
        {
          key: 'quality_status',
          label: { en: 'Quality Sahi hai ya nahi ?', hi: 'क्वालिटी सही है या नहीं?' },
          type: 'select',
          options: ['Passed - OK / Sahi Hai', 'Rejected / Sahi Nahi Hai'],
          required: true,
        },
      ],
      branches: [
        {
          when: { field: 'quality_status', equals: 'Rejected / Sahi Nahi Hai' },
          action: 'CLOSE',
        },
      ],
      on_complete: 'NEXT',
    },
    {
      step_no: 5,
      label: { en: 'Rate & Discount Check', hi: 'बिल व डिस्काउंट जांच (Rate & Discount Check)' },
      assignee: { type: 'DIRECT_USER_PHONE', phone: '7879883549', name: 'Sanjay Malakar' },
      is_important: true,
      tat: { kind: 'FIXED_HOURS', hours: 9 },
      visible_data: ['fabric_name', 'order_quantity', 'unit', 'rate', 'discount_percent', 'agent_name'],
      questions: [
        {
          key: 'rate_check_ok',
          label: { en: 'Rate Sahi hai bill mein ?', hi: 'रेट सही है बिल में?' },
          type: 'select',
          options: ['Yes / Haan', 'No / Nahi'],
          required: true,
        },
        {
          key: 'discount_check_ok',
          label: { en: 'Discount % Sahi hai bill me?', hi: 'डिस्काउंट % सही है बिल में?' },
          type: 'select',
          options: ['Yes / Haan', 'No / Nahi'],
          required: true,
        },
        {
          key: 'tally_entry_done',
          label: { en: 'Tally mein Entry Hogyi?', hi: 'टैली में एंट्री हो गयी?' },
          type: 'select',
          options: ['Yes / Haan', 'No / Nahi'],
          required: true,
        },
      ],
      on_complete: 'NEXT',
    },
    {
      step_no: 6,
      label: { en: 'Payment Initiate', hi: 'भुगतान शुरू करें (Payment Initiate)' },
      assignee: { type: 'DIRECT_USER_PHONE', phone: '7879883549', name: 'Sanjay Malakar' },
      is_important: true,
      tat: { kind: 'FIXED_HOURS', hours: 9 },
      visible_data: ['fabric_name', 'order_quantity', 'unit', 'rate', 'discount_percent', 'agent_name'],
      questions: [
        {
          key: 'payment_initiated',
          label: { en: 'Payment Initiate Kardiya?', hi: 'पेमेंट इनीशिएट कर दिया?' },
          type: 'select',
          options: ['Yes / Haan', 'No / Nahi'],
          required: true,
        },
      ],
      on_complete: 'CLOSE',
    },
  ],
};
